version: "3"
services:
  mysql:
    env_file: "./docker-compose-env/database.env"
    image: mysql:8.0.39
    ports:
      - "33061:3306"
    command: --init-file /data/application/init.sql
    volumes:
      - ./database/init.sql:/data/application/init.sql
  nginx:
    restart: always
    depends_on:
      - backend
      - frontend
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"
  backend:
    env_file:
      - path: "./docker-compose-env/database.env"
      - path: "./docker-compose-env/backend.env"
    depends_on:
      - mysql
    build:
      dockerfile: Dockerfile
      context: backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    ports:
      - "5000:5000"
  frontend:
    stdin_open: true
    build:
      dockerfile: Dockerfile
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
