version: "3"

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-app-cyclone:${BUILD_NUMBER}
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend-app-cyclone:${BUILD_NUMBER}
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend-app-cyclone:${BUILD_NUMBER}
    
  mysql:
    image: mysql:8.0
    env_file: "./docker-compose-env/database.env"
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "33061:3306"

volumes:
  mysql-data:
